name: build-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to build'
        required: true
        default: '1.X.X'

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Create directory structure
        run: |
          mkdir -p nxm-collection-dl
          cp __init__.py nxm-collection-dl/
          cp __meta__.py nxm-collection-dl/
          cp api.py nxm-collection-dl/
          cp gui.py nxm-collection-dl/
          cp LICENSE nxm-collection-dl/
          cp README.md nxm-collection-dl/
          cp var.py nxm-collection-dl/

      - name: Create release archive
        run: |
          zip -r nxm-collection-dl-${{ github.event.inputs.version }}.zip nxm-collection-dl/

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: "${{ github.event.inputs.version }}"
          body: "NXM Collection Downloader v${{ github.event.inputs.version }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: nxm-collection-dl-${{ github.event.inputs.version }}.zip
          asset_name: nxm-collection-dl-${{ github.event.inputs.version }}.zip
          asset_content_type: application/zip
